### ISSUE TITLE
Comtrya Variant Syntax

### ISSUE THREAD

**Issue by rawkode** [thebino/dotfiles#1]
This is severely under documented, but I thought I'd share.

Currently, you have:

```yaml
actions:
  - action: package.install
    where: os.name == "macos"
    provider: homebrew
    name: bat

  - action: package.install
    where: os.name == "linux"
    provider: aptitude
    name: bat
```

This is fine, but you could do:

```yaml
actions:
  - action: package.install
    name: bat
```

Because the provider defaults based on the operating system, meaning that it'll use aptitude on Debian like systems and brew on macOS.

Of course, there are cases where the package name is different across package managers and for that you can do:

```yaml
actions:
  - action: package.install
    name: bat
    variants:
    - where: os.name == "macos"
      name: macos-bat
```

Hope this helps. Do let us know if there's anything you need from Comtrya that it can't do.

Cheers
